// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: kratosmicoservice/app/app_wxMini/api/api.proto

package api

import (
	"context"

	bm "github.com/bilibili/kratos/pkg/net/http/blademaster"
	"github.com/bilibili/kratos/pkg/net/http/blademaster/binding"
)
import goods_service_v1 "kratosmicoservice/service/service_goods/api"

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

var PathWxMiniGoodsDetail = "wx/goods/detail"

// WxMiniBMServer is the server API for WxMini service.
type WxMiniBMServer interface {
	GoodsDetail(ctx context.Context, req *goods_service_v1.GoodsReq) (resp *goods_service_v1.GoodsRes, err error)
}

var WxMiniSvc WxMiniBMServer

func wxMiniGoodsDetail(c *bm.Context) {
	p := new(goods_service_v1.GoodsReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := WxMiniSvc.GoodsDetail(c, p)
	c.JSON(resp, err)
}

// RegisterWxMiniBMServer Register the blademaster route
func RegisterWxMiniBMServer(e *bm.Engine, server WxMiniBMServer) {
	WxMiniSvc = server
	e.GET("wx/goods/detail", wxMiniGoodsDetail)
}
