// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kratosmicoservice/app/app_wxMini/api/api.proto

package api

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	api "kratosmicoservice/service/service_goods/api"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("kratosmicoservice/app/app_wxMini/api/api.proto", fileDescriptor_255381e6c7b13886)
}

var fileDescriptor_255381e6c7b13886 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0xcb, 0x2e, 0x4a, 0x2c,
	0xc9, 0x2f, 0xce, 0xcd, 0x4c, 0xce, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x4f, 0x2c,
	0x28, 0x00, 0xe1, 0xf8, 0xf2, 0x0a, 0xdf, 0xcc, 0xbc, 0x4c, 0xfd, 0xc4, 0x02, 0x30, 0xd6, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x84, 0x88, 0xea, 0x41, 0x15, 0xeb, 0x95, 0x19, 0x4a, 0xe9,
	0xa6, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0xa7, 0xe7, 0xa7, 0xe7, 0xeb,
	0x83, 0x55, 0x26, 0x95, 0xa6, 0x81, 0x79, 0x60, 0x0e, 0x98, 0x05, 0x31, 0x41, 0x4a, 0x3a, 0x3d,
	0x3f, 0x3f, 0x3d, 0x27, 0x15, 0xa1, 0x2a, 0x35, 0xb7, 0xa0, 0xa4, 0x12, 0x2a, 0x29, 0x03, 0x95,
	0x04, 0x5b, 0x9a, 0x97, 0x97, 0x5f, 0x92, 0x58, 0x92, 0x99, 0x9f, 0x57, 0x0c, 0x95, 0x35, 0xc5,
	0x74, 0x2c, 0x1a, 0x1d, 0x9f, 0x9e, 0x9f, 0x9f, 0x52, 0x8c, 0xea, 0x66, 0xa3, 0x0c, 0x2e, 0xb6,
	0x70, 0xb0, 0xab, 0x85, 0xe2, 0xb8, 0xb8, 0xdd, 0x41, 0x0a, 0x5c, 0x52, 0x4b, 0x12, 0x33, 0x73,
	0x84, 0xa4, 0xf4, 0xc0, 0xca, 0x91, 0x3c, 0xa3, 0x07, 0x96, 0x0e, 0x4a, 0x2d, 0x94, 0xc2, 0x2d,
	0x57, 0xac, 0x24, 0xde, 0x74, 0xf9, 0xc9, 0x64, 0x26, 0x41, 0x21, 0xfe, 0xf2, 0x0a, 0x7d, 0x88,
	0x85, 0x29, 0x60, 0x03, 0x9d, 0x24, 0x4f, 0x3c, 0x94, 0x63, 0x38, 0xf1, 0x48, 0x8e, 0xf1, 0xc2,
	0x23, 0x39, 0xc6, 0x07, 0x8f, 0xe4, 0x18, 0x67, 0x3c, 0x96, 0x63, 0x88, 0x62, 0x4e, 0x2c, 0xc8,
	0x4c, 0x62, 0x03, 0xbb, 0xc5, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x7e, 0xf7, 0x24, 0xd5, 0x71,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WxMiniClient is the client API for WxMini service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WxMiniClient interface {
	GoodsDetail(ctx context.Context, in *api.GoodsReq, opts ...grpc.CallOption) (*api.GoodsRes, error)
}

type wxMiniClient struct {
	cc *grpc.ClientConn
}

func NewWxMiniClient(cc *grpc.ClientConn) WxMiniClient {
	return &wxMiniClient{cc}
}

func (c *wxMiniClient) GoodsDetail(ctx context.Context, in *api.GoodsReq, opts ...grpc.CallOption) (*api.GoodsRes, error) {
	out := new(api.GoodsRes)
	err := c.cc.Invoke(ctx, "/wxMini.service.v1.WxMini/GoodsDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WxMiniServer is the server API for WxMini service.
type WxMiniServer interface {
	GoodsDetail(context.Context, *api.GoodsReq) (*api.GoodsRes, error)
}

// UnimplementedWxMiniServer can be embedded to have forward compatible implementations.
type UnimplementedWxMiniServer struct {
}

func (*UnimplementedWxMiniServer) GoodsDetail(ctx context.Context, req *api.GoodsReq) (*api.GoodsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GoodsDetail not implemented")
}

func RegisterWxMiniServer(s *grpc.Server, srv WxMiniServer) {
	s.RegisterService(&_WxMini_serviceDesc, srv)
}

func _WxMini_GoodsDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.GoodsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WxMiniServer).GoodsDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wxMini.service.v1.WxMini/GoodsDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WxMiniServer).GoodsDetail(ctx, req.(*api.GoodsReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _WxMini_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wxMini.service.v1.WxMini",
	HandlerType: (*WxMiniServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GoodsDetail",
			Handler:    _WxMini_GoodsDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kratosmicoservice/app/app_wxMini/api/api.proto",
}
